name: DevOps Base CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x scripts/healthcheck.sh

      - name: Run healthcheck dry-run test
        run: |
          echo "Testing script execution..."
          bash -n scripts/healthcheck.sh
